### ISSUE TITLE
Deprecation messages by execute commands via console

### ISSUE THREAD

**Issue by hacksch** [tomasnorre/crawler#1011] opened 2023-05-08 06:48 UTC
## Bug Report

Hello Tomas,

when i run the database:updateschema or flush entries command via command line, i recieve te following deprecation messages.

```
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/aoeweb/htdocs/typo3conf/ext/crawler/Classes/Command/BuildQueueCommand.php on line 137
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/aoeweb/htdocs/typo3conf/ext/crawler/Classes/Command/BuildQueueCommand.php on line 139
```

**Expected behavior/output**
No deprectation messages should be shown

**Steps to reproduce**
run the database:updateschema or flush entries command via vendor/bin/typo3cms

**Environment**
- Crawler version(s): 11.0.7
- TYPO3 version(s): 11.5.26
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Comment by hacksch** [comment] 2023-05-08 09:07
Deprecated since PHP 8.2
https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated

**Comment by Finulin** [comment] 2023-08-23 07:36
The problem needs to be fixed urgently as it causes deployment errors

**Comment by tomasnorre** [comment] 2023-08-24 10:02
PRs are more than welcome.

**Comment by tbal** [comment] 2024-03-05 09:06
duplicate of #1007 
PR #999

**Comment by tbal** [comment] 2024-03-05 09:58
Just added a PR for v11.x branch #1030.
PR for main branch is #999.

**Comment by tomasnorre** [comment] 2024-03-05 10:40
Thanks a bunch.

**Comment by tomasnorre** [comment] 2024-03-05 10:47
Is now resolve in both branches that support php 8.2, main and v11.x. 
The change isn't released yet though.

**Closed by tomasnorre** 2024-03-05 10:47 UTC
Labels: Bug, duplicate, TYPO3v11, v12.x
