### ISSUE TITLE
crawler:buildQueue failed by warning under PHP 8.1

### ISSUE THREAD

**Issue by hacksch** [tomasnorre/crawler#984] opened 2022-11-17 11:54 UTC
## Bug Report

**Current Behavior**
When i execute crawler:buildQueue via console i get the following message and the process stops

"[ TYPO3\CMS\Core\Error\Exception ]
  Warning: Undefined array key "log" in /var/www/aoeweb/htdocs/typo3conf/ext/crawler/Classes/Command/BuildQueueComman
  d.php line 187"

**Expected behavior/output**
Command should be executed successful

**Environment**
- Crawler version(s): 11.0.6
- TYPO3 version(s): 11.5.19
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- PHP version: PHP 8.1.12

**Possible Solution**
Add a check if array key exists in line 187 -> "$resLog = array_key_exists('log', $requestResult) && is_array($requestResult['log']) ? PHP_EOL . chr(9) . chr(9) . implode("

**Comment by tomasnorre** [comment] 2022-11-17 12:01
Thanks for the report. I'll make sure it gets correct, and included in the next release.

**Comment by tomasnorre** [comment] 2022-11-18 09:52
@hacksch Can you please verify that the PR is solving your problem? 
I could not reproduce it locally, but the check has no harm, and is safer to check like this.

So I'm OK with the change. 
If you verify that it works, I'll create a new 11.0.7 release.

**Comment by hacksch** [comment] 2022-11-18 15:18
@tomasnorre Works perfect. Thanks Tomas

**Comment by tomasnorre** [comment] 2022-11-18 15:43
Then I'll have it merged and create a new release.

**Comment by tomasnorre** [comment] 2022-11-18 15:59
Fix with the 11.0.7 release 

https://extensions.typo3.org/extension/crawler
https://packagist.org/packages/tomasnorre/crawler#11.0.7

#HappyCrawling

**Closed by tomasnorre** 2022-11-18 15:59 UTC
Labels: Bug, v11.x, v12.x, backport, PHP8.1
