### ISSUE TITLE
Crawler Configuration: No Processing instruction filter shown

### ISSUE THREAD

**Issue by heuchri56** [tomasnorre/crawler#960] opened 2022-10-26 11:54 UTC
In my installation (Typo3 11.5.17, PHP 8.1, MySQL 8.0.27, bootstrap_package, news, indexed_search and crawler) no processing instruction filter is shown in the backend while adding or editing a crawler configuration. An indexer configuration for indexed_search is in the root page together with the crawler configuration record.
I have added the instruction tx_indexedsearch_reindex manually to the database record. Indexing triggered by scheduler / cronjob works so far with this entry.
Many thanks and regards, Christoph

**Comment by ArchonSlime** [comment] 2022-10-26 12:58
I encountered the same problem yesterday and was trying to find a solution. I found this that could be the cause for this issue, if it can be of any help.
[Breaking: #93110 - Indexed search does not provide hook for EXT:crawler anymore](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Breaking-93110-IndexedSearchDoesNotProvideHookForEXTcrawlerAnymore.html?highlight=crawler)

**Comment by tomasnorre** [comment] 2022-10-28 05:15
@heuchri56 Can you please let me know what you added to the database. 
My setup is still working locally after upgrading to the versions that you reported the error with, but I might have a left over in the DB.

**Comment by tomasnorre** [comment] 2022-10-28 06:00
I have just set up a new TYPO3 instance, and there I can reproduce the problem. So it's a left over in my dev-environment.

**Comment by heuchri56** [comment] 2022-10-28 06:02
After saving the configuration cantuscrawler1 in the backend I found the field processing_instruction_filter in the table tx_crawler_configuration being empty and entered tx_indexedsearch_reindex manually. Before this change indexing did not take place, afterwards yes. But I am not sure whether this success was really caused by populating this field.

 



 

Von: Tomas Norre Mikkelsen ***@***.***> 
Gesendet: Freitag, 28. Oktober 2022 07:15
An: tomasnorre/crawler ***@***.***>
Cc: heuchri56 ***@***.***>; Mention ***@***.***>
Betreff: Re: [tomasnorre/crawler] Crawler Configuration: No Processing instruction filter shown (Issue #960)

 

@heuchri56 <https://github.com/heuchri56>  Can you please let me know what you added to the database.
My setup is still working locally after upgrading to the versions that you reported the error with, but I might have a left over in the DB.

**Comment by tomasnorre** [comment] 2022-10-28 06:27
@heuchri56 Which part wasn't working for you? The indexing or the search? 
for me the indexing is working but regardless of search string, no results are shown.

**Comment by heuchri56** [comment] 2022-10-28 06:30
If I remember right, the indexing statistics did not show any results / “not indexed” so I interpreted it as not having indexed. The search results were empty as well.

 

Von: Tomas Norre Mikkelsen ***@***.***> 
Gesendet: Freitag, 28. Oktober 2022 08:27
An: tomasnorre/crawler ***@***.***>
Cc: heuchri56 ***@***.***>; Mention ***@***.***>
Betreff: Re: [tomasnorre/crawler] Crawler Configuration: No Processing instruction filter shown (Issue #960)

 

@heuchri56 <https://github.com/heuchri56>  Which part wasn't working for you? The indexing or the search?
for me the indexing is working but regardless of search string, no results are shown.

**Comment by tomasnorre** [comment] 2022-10-28 09:59
@heuchri56 @ArchonSlime would you mind testing the PR and give me some response.

**Comment by ArchonSlime** [comment] 2022-10-28 13:15
On my side, it fixed the issue, the Processing instruction filter is now showing like it was on my older typo3 (8.7 and 9.5). 
For me, adding it manualy in the database or selecting it with this new fix produced the same results. The crawler is able to crawl and it indexes pages. The search engine is also working.

**Comment by tomasnorre** [comment] 2022-10-28 13:26
Thanks for confirming.

**Comment by heuchri56** [comment] 2022-10-28 15:33
Works well in my installation – observed the same as ArchonSlime.

Many thanks!

 

Von: ArchonSlime ***@***.***> 
Gesendet: Freitag, 28. Oktober 2022 15:16
An: tomasnorre/crawler ***@***.***>
Cc: heuchri56 ***@***.***>; Mention ***@***.***>
Betreff: Re: [tomasnorre/crawler] Crawler Configuration: No Processing instruction filter shown (Issue #960)

 

On my side, it fixed the issue, the Processing instruction filter is now showing like it was on my older typo3 (8.7 and 9.5).
For me, adding it manualy in the database or selecting it with this new fix produced the same results. The crawler is able to crawl and it indexes pages. The search engine is also working.

**Comment by tomasnorre** [comment] 2022-10-29 07:35
Thanks, will have this merged, and back ported to the 11.x branch and create a new release.

**Closed** 2022-10-29 07:35 UTC
